# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path:
train:
  - /NAS3/lbliao/Data/MXB/segment/第一批/dataset/1024/train/images
  - /NAS3/lbliao/Data/MXB/segment/YNZL修订/dataset/1024/train/images
  - /NAS3/lbliao/Data/MXB/segment/神经节补充数据/dataset/1024/train/images
  - /NAS3/lbliao/Data/MXB/segment/补充神经节标注/dataset/1024/train/images
val:
  - /NAS3/lbliao/Data/MXB/segment/第一批/dataset/1024/val/images
  - /NAS3/lbliao/Data/MXB/segment/YNZL修订/dataset/1024/val/images
  - /NAS3/lbliao/Data/MXB/segment/神经节补充数据/dataset/1024/val/images
  - /NAS3/lbliao/Data/MXB/segment/补充神经节标注/dataset/1024/val/images
test:
  - /NAS3/lbliao/Data/MXB/segment/第一批/dataset/1024/test/images
  - /NAS3/lbliao/Data/MXB/segment/YNZL修订/dataset/1024/test/images
  - /NAS3/lbliao/Data/MXB/segment/神经节补充数据/dataset/1024/test/images
  - /NAS3/lbliao/Data/MXB/segment/补充神经节标注/dataset/1024/test/images
names:
    0: Benign
    1: Malignant
#    2: Other
